# Main
brew 'atuin'
brew 'micro'

# Kubernetes
brew 'kubernetes-cli'
brew 'kustomize'
brew 'krew'
brew 'k9s'
brew 'kubeseal'
brew 'argocd'
brew 'helm'
brew 'siderolabs/tap/talosctl'
brew 'k0sproject/tap/k0sctl'
brew 'hashicorp/tap/terraform'
brew 'cmctl' # cert-manager
