tap 'k0sproject/tap'
tap 'int128/kubelogin'
tap 'robusta-dev/homebrew-krr'
tap 'hashicorp/tap'
tap 'siderolabs/tap'
tap 'kdash-rs/kdash'

# Main
brew 'atuin'
brew 'micro'
brew 'git-delta'

# Kubernetes
brew 'kubernetes-cli'
brew 'kustomize'
brew 'k9s'
brew 'popeye'
brew 'kubeseal'
brew 'argocd'
brew 'helm'
brew 'k0sproject/tap/k0sctl'
brew 'int128/kubelogin/kubelogin'
brew 'kubectl-cnpg'
brew 'kubectl-rook-ceph'
brew 'robusta-dev/homebrew-krr/krr'
brew 'kdash-rs/kdash/kdash'
brew 'cilium-cli'
brew 'cmctl' # cert-manager

# Kubernetes: Talos
brew 'talhelper'
brew 'siderolabs/tap/talosctl'

# DevOps Tools
brew 'dive'
brew 'trivy'
brew 'hashicorp/tap/terraform'
brew 'go-task'
brew 'opentofu'

# Container Tools
brew 'skopeo'

# ZSH
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'oh-my-posh'

# Python
brew 'ruff'
