# Main
brew 'atuin'
brew 'micro'

# Kubernetes
brew 'kubernetes-cli'
brew 'kustomize'
brew 'k9s'
brew 'kubeseal'
brew 'trivy'
brew 'argocd'
brew 'helm'
brew 'siderolabs/tap/talosctl'
brew 'k0sproject/tap/k0sctl'
brew 'hashicorp/tap/terraform'
brew 'int128/kubelogin/kubelogin'
brew 'cmctl' # cert-manager
brew 'kubectl-cnpg'
brew 'kubectl-rook-ceph'

# ZSH
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'powerlevel10k'
