#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "$(readlink -f -- "$0" || echo "$0")")" && pwd)

alias t='terraform'
alias k='kubectl'
alias d='docker'
alias dc='docker compose'

brewfile() {
  cd "$SCRIPT_DIR/../brew" || return
  brew bundle "$1"

  if command -v kubectl &> /dev/null && kubectl krew version &> /dev/null; then
    kubectl krew update
    kubectl krew install rook-ceph
    kubectl krew install oidc-login
    kubectl krew install cnpg
  fi
}
