#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "$(readlink -f -- "$0" || echo "$0")")" && pwd)

alias t='tofu'
alias k='kubectl'
alias d='docker'
alias dc='docker compose'

brewfile() {
  (
    cd "$SCRIPT_DIR/../brew" || return
    brew bundle "$1"
  )
}
