k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    skin: custom
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: public.ecr.aws/docker/library/busybox:stable
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: true
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 250
    buffer: 5000
    sinceSeconds: -1
    fullScreen: false
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
