#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "$(readlink -f -- "$0" || echo "$0")")" && pwd)

alias t='terraform'
alias k='kubectl'
alias d='docker'
alias dc='docker compose'

install_krew_plugins() {
  if command -v kubectl &> /dev/null && kubectl krew version &> /dev/null; then
    kubectl krew update
    kubectl krew install rook-ceph
    kubectl krew install oidc-login
    kubectl krew install cnpg
  fi
}
alias brewfile='(cd "$SCRIPT_DIR/../brew" && brew bundle install && install_krew_plugins)'
